package lt.bit.products.ui.service.error;

public enum ErrorCode {
  VALUE_TOO_SHORT, EMPTY_VALUE, NEGATIVE_NUMBER, PRODUCT_NOT_FOUND, INVALID_FILE_TYPE, FILE_TOO_LARGE,
  PASSWORD_REQUIRED, ALL_FIELDS_REQUIRED, PASSWORDS_DO_NOT_MATCH
}
